authors = ["Author1", "Author2"]
logging = true
name = "A1K9"
output = "docs"
static_assets = ["a1k9/assets"] # Public files 
verbose = false
version = "0.01"

[[page]]
description = "Gaynor Probert K9 Behaviour and Training - Improving relationships between dogs and their owners"
path = "/"
slug = "index"
title = "Dog Behaviour and Trainer South Wales | A1K9 Training"
view = "pages/index.tera"
