authors = ["Author1", "Author2"]
name = "Your Website Name"
version = "0.01"

[[page]]
controller = "index.rs"
path = "/"
slug = "index"
title = "My Page Title"
view = "views/index.hbs"

[[page]]
components = ["partials/authors.html", "partials/me.md"]
controller = "about.rs"
model = "models/about.json"
slug = "about"
title = "About Us"
view = "views/about.hbs"

[[pages]]
controller = "course.js"
model = "courses"
path = "courses"
view = "courses/course.hbs"

static = ["public", "_generated"]
